const SERVER_ORIGIN = 'localhost';
const PORT = 80;
const isPROD = false;
const TURNSTYLE_SITE_KEY = "0x4AAAAAAA_eBARb9L5VixBM";
const npm_package_version = "1.0.0";
const TURN2_SHARED_SECRET = "";
const ANDROID_APP_PACKAGE = "info.dvkr.screenstream";
const ANDROID_APP_CERT256 = "67:80:30:DE:17:FD:A4:B8:B2:1D:9F:D3:57:0D:5C:FB:2D:57:86:7C:46:51:70:06:22:3D:7D:1F:B0:7F:39:AC";
const GOOGLE_SERVICE_ACCOUNT_EMAIL = "cuongnl@vtdglobal.com";
const TURNSTYLE_SECRET_KEY = "0x4AAAAAAA_eBEa5RK17uYFtDUmHmzMTDFc";
const GOOGLE_SERVICE_ACCOUNT_KEY = "AIzaSyBmrBALh2YTlMV8id9r4dO6FYXMBe5_ti4";

module.exports = {
    SERVER_ORIGIN,
    PORT,
    isPROD,
    TURNSTYLE_SITE_KEY,
    npm_package_version,
    TURN2_SHARED_SECRET,
    ANDROID_APP_PACKAGE,
    ANDROID_APP_CERT256,
    GOOGLE_SERVICE_ACCOUNT_EMAIL,
    TURNSTYLE_SECRET_KEY,
    GOOGLE_SERVICE_ACCOUNT_KEY
}